name: aspectd
description: AOP for Flutter. AspectD is an AOP(aspect oriented programming) framework for dart. It provides call&execute&inject grammar.
version: 0.9.7
homepage: https://github.com/alibaba-flutter/aspectd

environment:
  sdk: ">=2.3.0 <3.0.0"

dev_dependencies:
  kernel: any
  front_end: any
  args: any
  path: any
  yaml: any
  _fe_analyzer_shared: any
  mockito: 4.1.1
  test: 1.9.4

dependency_overrides:
  kernel:
    git:
      url: https://github.com/dart-lang/sdk.git
      ref: 5ae5aff6406addf8356aae649e626d262de624cb
      path: pkg/kernel
  front_end:
    git:
      url: https://github.com/dart-lang/sdk.git
      ref: 5ae5aff6406addf8356aae649e626d262de624cb
      path: pkg/front_end
  _fe_analyzer_shared:
    git:
      url: https://github.com/dart-lang/sdk.git
      ref: 5ae5aff6406addf8356aae649e626d262de624cb
      path: pkg/_fe_analyzer_shared
  analyzer:
    git:
      url: https://github.com/dart-lang/sdk.git
      ref: 5ae5aff6406addf8356aae649e626d262de624cb
      path: pkg/analyzer

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.

