name: aspectd
description: AOP for Flutter. AspectD is an AOP(aspect oriented programming) framework for dart. It provides call&execute&inject grammar.
version: 0.9.5
author: KyleWong<kang.wang1988@gmail.com>
homepage: https://github.com/alibaba-flutter/aspectd

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dev_dependencies:
  kernel: any
  front_end: any
  args: any
  path: any
  yaml: any

dependency_overrides:
  kernel:
    git:
      url: https://github.com/dart-lang/sdk.git
      ref: 7505b3a5f07cfbcd920e2aeeae5581c5337b859a
      path: pkg/kernel
  front_end:
    git:
      url: https://github.com/dart-lang/sdk.git
      ref: 7505b3a5f07cfbcd920e2aeeae5581c5337b859a
      path: pkg/front_end


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.

