name: aspectd
description: AOP for Flutter. AspectD is an AOP(aspect oriented programming) framework for dart. It provides call&execute&inject grammar.
version: 0.9.6
author: KyleWong<kang.wang1988@gmail.com>
homepage: https://github.com/alibaba-flutter/aspectd

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dev_dependencies:
  kernel: any
  front_end: any
  args: any
  path: any
  yaml: any

dependency_overrides:
  kernel:
    git:
      url: https://github.com/dart-lang/sdk.git
      ref: ab5cf0f854f4cae1c0adad5f7a8aa158b1d646ca
      path: pkg/kernel
  front_end:
    git:
      url: https://github.com/dart-lang/sdk.git
      ref: ab5cf0f854f4cae1c0adad5f7a8aa158b1d646ca
      path: pkg/front_end
  _fe_analyzer_shared:
    git:
      url: https://github.com/dart-lang/sdk.git
      ref: ab5cf0f854f4cae1c0adad5f7a8aa158b1d646ca
      path: pkg/_fe_analyzer_shared


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.

